#!/bin/sh
raspivid -t 0 -b 2000000  -fps 60 -w 640 -h 480 -n -o - | gst-launch-1.0 -q fdsrc ! h264parse ! rtph264pay pt=96 config-interval=5 ! udpsink host=255.255.255.255 port=5001 2>&1 /dev/null &

